### ISSUE TITLE
What is this!?

### ISSUE THREAD

**Issue by dori4n** [mixer/cdk-issues#1]
> @connor4312 :
> * Editor state may contain private or confidential data which the user doesn't want to share.

Exactly. That means no automatic uploads of diagnostic reports **at all** unless I opt-in, whether you want to have them, encrypt and secure transmission, or not. Thank you so much.

PS: Did I mention this is illegal without prompting the user for consent first? I've been shown no end-user agreement when installing or opening the CDK application, least of which any agreement which mentions this...

**Comment by dori4n** [comment]
And dear heavens, even worse, it prefills the form with the information by passing the data via query string in a GET request to GitHub, meaning GitHub ***is*** actually sent the password for the *"encrypted"* data you shouldn't even send along in the first place...

**Comment by ProbablePrime** [comment]
This is now opt in.
